### ISSUE TITLE
Add thread safe API to rythm engine

### ISSUE THREAD

**Issue by greenlaw110** [rythmengine/rythmengine#20]
The current rythm engine API is not thread-safe. [Play-rythm](https://github.com/greenlaw110/play-rythm) has implemented it's own thread-safe solution (see [RythmTemplateLoader.java](https://github.com/greenlaw110/play-rythm/blob/master/src/com/greenlaw110/rythm/play/RythmTemplateLoader.java#L236)). It needs to create an native thread-safe API so that rythm could be used in other server/containers easily

**Comment by WolfgangFahl** [comment]
I think I am hit by the thread safety issue and I'm in need for an explanation of how to tackle the situation.

**Comment by JensRantil** [comment]
> I think I am hit by the thread safety issue and I'm in need for an explanation of how to tackle the situation.

@WolfgangFahl I think we might be, too. Out of four application servers running the exact same setup, one application instance complains that a variable is null when it most definitely is hardcoded into the map given to `Rythm#render`. Restarting the JVM made the problem go away. This is the second time we are seeing this. We are running `rythm-engine` version `1.0.1`.

FYI, @JonNilsson and @eripe970.
