### ISSUE TITLE
Strings indentation does not work

### ISSUE THREAD

**Issue by sramazzina** [rythmengine/rythmengine#217]
Hi,

I'm using rythm in an application we're developing internally to generate java code and XML files. Unfortunately, I noticed that even if my template file is indented the output of the generated file is not indented. It seems like to template engine during the file generation does not preserve the left spaces/tabs that contribute to indentation. Is this kind of behavior a bug? In case it isn't, how can I generate an indented output file?

Thank you very much for your support and help.

Sergio

**Comment by JananiRam** [comment]
How do you set that value as false??

**Comment by greenlaw110** [comment]
@JananiRam refer to http://rythmengine.org/doc/developer_guide.md#configuration
