### ISSUE TITLE
enum declaration support missing

### ISSUE THREAD

**Issue by WolfgangFahl** [rythmengine/rythmengine#266]
@{
class Foo {
   enum Language {
	 de, en,fr,es
   };
   public Language lang;
   Foo(Language lang) {
      this.lang=lang;
   }
}

Foo foo = new Foo(Language.de);
}
lang is @foo.lang

leads to error:

org.rythmengine.exception.CompileException: The member enum Language can only be defined inside a top-level class or interface

in general the Java support should be more complete and not leave out certain constructs.

**Comment by greenlaw110** [comment]
@WolfgangFahl So I suppose #271 fixed this issue, can you please confirm?
