### ISSUE TITLE
@var@ quirks

### ISSUE THREAD

**Issue by WolfgangFahl** [rythmengine/rythmengine#268]
Rythm doesn't like to put `@something@somethingelse` close together.

The work-around `@(something)@(somethingelse)` works but if you forget it you get all kinds of strange errors. 

Looking for these errors is very time consuming and it would be best if the parser would be fixed. 
Having a parser generator in use would avoid most of these problems since it would follow the proposed syntax much more closely than Rythms hand crafted parser currently does.

**Comment by WolfgangFahl** [comment]
@// show the given Property
@def showProperty(String property) {
@property
}
@showProperty("Test1")@showProperty("Test")

has the same quirk it renders:
Test1showProperty("Test")

instead of Test1Test

**Comment by greenlaw110** [comment]
Workaround is @(showProperty("Test1"))@showProperty("Test")
