### ISSUE TITLE
1.1.2 Snapshot invalid import in sample

### ISSUE THREAD

**Issue by WolfgangFahl** [rythmengine/rythmengine#276]
import org.osgl.util.C;
import org.osgl.util.S;

is not resolved when cloning project in package package com.mycompany.app.model;

**Comment by greenlaw110** [comment]
The dependency has been specified in the `pom.xml` of the sample.

![image](https://cloud.githubusercontent.com/assets/216930/8348001/c3d553ca-1b50-11e5-9763-ea576003dd08.png)

And I can compile it without problem:
![image](https://cloud.githubusercontent.com/assets/216930/8348018/f3203ef6-1b50-11e5-9045-ccf248d0c6be.png)

**Comment by WolfgangFahl** [comment]
strange - my pom doesn't have it although I git fetched the upstream changes.

**Comment by greenlaw110** [comment]
Checkout https://github.com/greenlaw110/Rythm/blob/master/samples/demo_fo_SO_150529/pom.xml
![image](https://cloud.githubusercontent.com/assets/216930/8367248/b8d29b56-1bdf-11e5-99ac-9a9e38067a47.png)

**Comment by greenlaw110** [comment]
I think it's because I have two upstream of rythm repository, and I just pushed the change to github upstream about two days ago, and that's before you pick up the code from github

**Comment by WolfgangFahl** [comment]
I am sorry I didn't see that you were talking about a different pom. My Eclipse setup doesn't pick that pom up by itself.
