### ISSUE TITLE
failures in mvn test

### ISSUE THREAD

**Issue by WolfgangFahl** [rythmengine/rythmengine#280]
Results :

Failed tests:   formatCurrency(org.rythmengine.essential.UtilsTest): expected:<[$1,000.00]> but was:<[1.000,00 ?]>
  test227(org.rythmengine.issue.GhIssueTest): expected:<000[,010.]30> but was:<000[.010,]30>
  test227a(org.rythmengine.issue.GhIssueTest): expected:<000[,010.]30> but was:<000[.010,]30>

Tests run: 247, Failures: 3, Errors: 0, Skipped: 3

are these locale specific ?

**Comment by greenlaw110** [comment]
@WolfgangFahl it should be locale specific. Can you please fix this one as you can easily reproduce it?
