### ISSUE TITLE
Rythm is not documented as not thread safe

### ISSUE THREAD

**Issue by JensRantil** [rythmengine/rythmengine#287]
This came out of #286.

Proposal: Add JavaDoc to `Rythm` class to explicitly state that it is not thread safe.

**Comment by fpoliquin** [comment]
It should also be documented on the website. This is a major concern for us. If we'd known it wasn't thread safe, we probably would have choosen another template engine.

**Comment by JensRantil** [comment]
> If we'd known it wasn't thread safe, we probably would have choosen another template engine.

Couldn't agree more. Also, response is slow and the code is generally a mess when reading it.

**Comment by greenlaw110** [comment]
@igmar I would like to allocate this fix to 1.2. V2.0 should be a major release, e.,g. using antlr as the core parsing engine

**Comment by WolfgangFahl** [comment]
I think we can close this issue about the documentation and create a new issue for the thread safety.

**Comment by greenlaw110** [comment]
agreed
