### ISSUE TITLE
Nice Feature

### ISSUE THREAD

**Issue by WolfgangFahl** [rythmengine/rythmengine#290]
```
@def sayHelloTo(String who) {
    Hello @who!
}
@sayHelloTo("Rythm")
@sayHelloTo("Velocity")
@{
  org.rythmengine.utils.RawData text=sayHelloTo("me");
 String newtext=text.toString()+" now";
}
@text
@newtext
```

This works nicely. You might want to document it and may be add a syntax to hide the RawData ...

**Comment by greenlaw110** [comment]
Well you discovered a feature I don't even know ;-)

Actually replace `org.rythmengine.utils.RawData` with `Object` you get the same result
