### ISSUE TITLE
Add current version to maven central

### ISSUE THREAD

**Issue by andyHa** [rythmengine/rythmengine#320]
Somehow 1.1.4 is not in maven central? Could you please provide a release and deploy it to central (or sonatype releases which should be mirrored to central)

**Comment by greenlaw110** [comment]
Thanks @andyHa I will follow up. The current snapshot version is 1.1.5. I will see if I can push to central this weekend

**Comment by greenlaw110** [comment]
rythm-engine-1.1.5 released to central repository: http://search.maven.org#artifactdetails|org.rythmengine|rythm-engine|1.1.5|jar
