### ISSUE TITLE
mvn test fails on Windows 2012 server

### ISSUE THREAD

**Issue by WolfgangFahl** [rythmengine/rythmengine#339]
Tests run: 250, Failures: 6
e.g. testWithBlankInFront

**Comment by WolfgangFahl** [comment]
same on a Windows7 machine:

1. testWithBlankInFront
2. testInlineComment
3. testDirectiveInsideInlineComment
4. testRemoveSpaceTillLastLineBreak
5. testInlineCommentInsideDirectiveComment
6. test170

looks like this has mostly to do with the different newline character on windows machines.

**Comment by WolfgangFahl** [comment]
Green - could you please fix this - i need the rythmEngine to work properly in a windows environment.

**Comment by greenlaw110** [comment]
Is this a unit testing bug or a bug of the engine that must fixed to make it running on Windows? If it's a testing bug then it's not that urgent because we always build it on linux, right?

**Comment by WolfgangFahl** [comment]
The engine will fail on Windows since it generates wrong code since newlines after comments are not correctly detected. I assume a \r\n is expected where \n should suffice

**Comment by WolfgangFahl** [comment]
One of the failure reasons is in CommentParser.java see http://stackoverflow.com/a/4945676/1497139
Using %n in String.format introduces a platform specific newline character:
^(%s/.*?)(%n.*|$)

**Comment by WolfgangFahl** [comment]
Tests run: 293, Failures: 0, Errors: 0, Skipped: 6
we might switch off the double tests now to improve test performance ...
