### ISSUE TITLE
1.6 release on maven central

### ISSUE THREAD

**Issue by WolfgangFahl** [rythmengine/rythmengine#349]
The upgrade to 1.7-Snapshot breaks quite a few of my projects that depend on 1.6-Snapshot. Instead of the snapshot it would be good to be able to use a 1.6 release from maven central.

Unfortunately there is no 1.6 release I could find there:

http://search.maven.org/#search|gav|1|g%3A%22org.rythmengine%22%20AND%20a%3A%22rythm-engine%22

Please create a 1.6 release

**Comment by greenlaw110** [comment]
@WolfgangFahl I am on holiday. Will work on this when I come back

**Comment by WolfgangFahl** [comment]
I am happy with the 1.7 release
