### ISSUE TITLE
Warmup a template

### ISSUE THREAD

**Issue by JensRantil** [rythmengine/rythmengine#353]
Hi,

We notice that Rythm is quite slow when it is starting. Is it possible for us to load in the template files before starting our application?

Thanks, J

**Comment by greenlaw110** [comment]
Rythm provides a [local_precompiled](http://rythmengine.org/doc/configuration.md#engine_load_precompiled_enabled) configuration which allows the engine to load precompiled template bytecodes. However this does require your app or plugin like [play-rythm](https://www.playframework.com/modules/rythm) provides the feature that precompile the template files, in the case of play, the framework itself provides precompile option to parse/compile templates at build time.

**Comment by JensRantil** [comment]
@greenlaw110 Thanks for getting back to me about this.

There is no way for me, given an instantiated `RythmEngine`, to load the templates from file, compile to bytecode and populate the internal cache? I have a lost of template files I will use later and believe this would speed things up considerably.

Reason I am asking if that's a viable way forward is that I would avoid having to modify our build infrastructure to compile the templates offline.

**Comment by JensRantil** [comment]
Worked around this by calling `myRythmEngine.getTemplate(XXX)` for every template we have on startup. Definitely improved startup time.

**Comment by JensRantil** [comment]
@Mattias- FYI.
