### ISSUE TITLE
Concurrency issues with one Engine serving multiple locales

### ISSUE THREAD

**Issue by TLoD-Snake** [rythmengine/rythmengine#355]
Is it somehow possible to correctly concurrently render multiple templates with different locales with one RythmEngine?

My code looks like:
```
val engine = RythmEngineCache.engine(engineConf)
engine.prepare(locale)
engine.render(templateFileName, params.asJava)
```

I assume I'll got in problem if one thread will switch locale while other thread is in the middle of template rendering.

**Comment by greenlaw110** [comment]
no you won't. `engine.prepare(locale)` use `ThreadLocal` to store the locale data

**Comment by TLoD-Snake** [comment]
Thanks!
