### ISSUE TITLE
My numbers are getting rounded!

### ISSUE THREAD

**Issue by TLoD-Snake** [rythmengine/rythmengine#357]
Hi!

I have a template with `@i18n("message", name, index)` where index is Double value, in template I have args defined as `@args String name, Number index` and in lang file (resource) I have `message=<strong>{0}</strong> has reached <strong>{1}</strong>`
Index usually is something like 1.000034, where all decimal digits matter. But I'm getting it rounded to 1 in template.

**Comment by greenlaw110** [comment]
try
 
```
message=<strong>{0}</strong> has reached <strong>{1,number,#.#########}</strong>
```

See http://stackoverflow.com/questions/698261/how-do-you-format-a-fractional-percentage-with-java-text-messageformat

**Comment by TLoD-Snake** [comment]
Thanks a lot.
