### ISSUE TITLE
format issue

### ISSUE THREAD

**Issue by WolfgangFahl** [rythmengine/rythmengine#360]
Here is my motivation to not use format:
```
@{
 Double[] ds={2.5,1.0,3.1419,200.0,3.75};
}
@for (double d:ds) {
  @(d.format("#.##"))
}
```
result:

```
2.5
 1
 3.14
 200
 3.75
```

expected result:
```
2.50
 1.00
 3.14
 200.00
 3.75
```
or an explanation how the format parameters work. I thinks I'd also rather use the String.format format parameters which seem to be more flexible.

**Comment by greenlaw110** [comment]
Rythm use [DecimalFormat](http://docs.oracle.com/javase/6/docs/api/java/text/DecimalFormat.html) to format numbers. In your case, you should use `@d.format("0.00")`. Here are the relevant part in the JavaDoc about DecimalFormat:

![image](https://cloud.githubusercontent.com/assets/216930/24318053/836bfa50-1153-11e7-94c8-2c850387dce9.png)

And your case in rythmefiddle:

![image](https://cloud.githubusercontent.com/assets/216930/24318064/ab3c3838-1153-11e7-96f1-7951c345677f.png)
