### ISSUE TITLE
Rythm website is broken

### ISSUE THREAD

**Issue by Janosch** [rythmengine/rythmengine#374]
The layout of the documentation section of the rhythm website is messed up. Probably this is due to HTTP503 errors received by http://netdna.bootstrapcdn.com where the rythm website trys to get some CSS and JS files from.

![rhythm-http-503](https://user-images.githubusercontent.com/219138/36530767-3b9f5198-17bc-11e8-8b77-77581ee3b18b.png)

![rythm-website](https://user-images.githubusercontent.com/219138/36530769-3e7b61ea-17bc-11e8-962f-ecdd38e44994.png)

**Comment by greenlaw110** [comment]
hmm... I don't have an issue here:
![image](https://user-images.githubusercontent.com/216930/36547229-73398f1c-1841-11e8-966b-df4bd9b60012.png)

![image](https://user-images.githubusercontent.com/216930/36547250-83eb276c-1841-11e8-9bc9-a563e553a3bc.png)

Can you try again?
